# Assignment One

In [1]:
pip install mysql-connector-python

Note: you may need to restart the kernel to use updated packages.


In [2]:
import mysql.connector
 
mydb = mysql.connector.connect(
  host="localhost",
  user="root",
  password= "7@u*sqJX"   #REPLACE THIS WITH THE PASSWORD YOU SET
)
 
print(mydb)
 
if mydb.is_connected():
    print("CONNECTION SUCCESSFUL")


CONNECTION SUCCESSFUL


In [3]:
#create a database
mycursor = mydb.cursor()
mycursor.execute("DROP DATABASE IF EXISTS data1050f24")
mycursor.execute("CREATE DATABASE data1050f24")

In [4]:
mycursor = mydb.cursor()
mycursor.execute("SHOW DATABASES")

for x in mycursor:
  print(x)

('data1050f24',)
('information_schema',)
('mysql',)
('performance_schema',)
('sys',)


In [5]:
#create a table
mycursor = mydb.cursor()
mycursor.execute("DROP TABLE IF EXISTS data1050F24.department")
mycursor.execute('''CREATE TABLE data1050F24.department ( 
                    dept_name VARCHAR(128) PRIMARY KEY, 
                    building VARCHAR(128), 
                    budget INT)''')

In [6]:
mycursor = mydb.cursor()
mycursor.execute("DROP TABLE IF EXISTS data1050F24.student")
mycursor.execute('''CREATE TABLE data1050F24.student (
                    ID INT PRIMARY KEY,
                    name VARCHAR(128) NOT NULL,
                    dept_name VARCHAR(128),
                    tot_cred INT,
                    foreign key(dept_name) references data1050F24.department(dept_name)
                 )''')

In [7]:
mycursor = mydb.cursor()
mycursor.execute("DROP TABLE IF EXISTS data1050F24.instructor")
mycursor.execute('''CREATE TABLE data1050F24.instructor (
                    ID INT PRIMARY KEY,
                    name VARCHAR(128) NOT NULL,
                    dept_name VARCHAR(128),
                    salary INT,
                    check(salary >= 0),
                    foreign key(dept_name) references data1050F24.department(dept_name)
                    )''')

Connecting to a database and showing tables

In [8]:
#connect to a specific database
mydb = mysql.connector.connect(
  host="localhost",
  user="root",
  password= "7@u*sqJX", #REPLACE THIS WITH YOUR PASSWORD 
  database = "data1050f24" #connecting to testDatabase
)

In [9]:
mycursor = mydb.cursor()

mycursor.execute("SHOW TABLES")

for x in mycursor:
  print(x)

('department',)
('instructor',)
('student',)


In [10]:
import pandas as pd

In [11]:
pip install fsspec

Note: you may need to restart the kernel to use updated packages.


In [12]:
#point the path to where in your hard drive you have stored the file department.csv
data = pd.read_csv("department.csv")
data.head()

dept_name   building   budget
0     CompSci        CIT  4000000
1     AppMath   Pembroke  1000525
2        Econ     Watson  1230000
3  Philosophy    Athenia   300000
4     English  Litereria  1389400

In [13]:
data.dtypes

dept_name    object
building     object
budget        int64
dtype: object

In [14]:
for i,row in data.iterrows():
            sql = "INSERT INTO department VALUES (%s,%s,%s)"
            mycursor.execute(sql, tuple(row))
            print("Record inserted")
            # the connection is not autocommitted by default, so we 
            # must commit to save our changes
            mydb.commit()

Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted


In [15]:
query = "SELECT * from department"
mycursor.execute(query)

In [16]:
for x in mycursor:
    print(x)

('AppMath', 'Pembroke', 1000525)
('CompSci', 'CIT', 4000000)
('DSI', 'Angell', 750000)
('Econ', 'Watson', 1230000)
('English', 'Litereria', 1389400)
('Math', 'Pembroke', 999785)
('Philosophy', 'Athenia', 300000)
('Psychology', 'Skinner', 1223350)
('Sociology', 'Watson', 789000)


In [17]:
#point the path to where in your hard drive you have stored the file student.csv
data = pd.read_csv("student.csv")
data.head()

ID         name   dept_name  tot_cred
0  1238   John Smith         DSI         4
1  1645     Jane Doe  Philosophy         9
2  1888  Chuning Liu     CompSci         5
3  1970  Stan Ambani        Econ         0
4  1845    Jane Chen         DSI         2

In [18]:
data.dtypes

ID            int64
name         object
dept_name    object
tot_cred      int64
dtype: object

In [19]:
for i,row in data.iterrows():
            sql = "INSERT INTO student VALUES (%s,%s,%s, %s)"
            mycursor.execute(sql, tuple(row))
            print("Record inserted")
            # the connection is not autocommitted by default, so we 
            # must commit to save our changes
            mydb.commit()

Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted


In [20]:
query = "SELECT * from student"
mycursor.execute(query)

In [21]:
for x in mycursor:
    print(x)

(1122, 'Julia Rodriguez', 'AppMath', 8)
(1221, 'Ivan Petrov', 'Psychology', 9)
(1238, 'John Smith', 'DSI', 4)
(1298, 'Marvel Comic', 'Psychology', 6)
(1333, 'Mukesh Modi', 'DSI', 7)
(1444, 'Suresh Verma', 'English', 4)
(1455, 'Molly Bloom', 'English', 5)
(1645, 'Jane Doe', 'Philosophy', 9)
(1845, 'Jane Chen', 'DSI', 2)
(1881, 'Holly Zheng', 'Sociology', 5)
(1888, 'Chuning Liu', 'CompSci', 5)
(1934, 'Boris Pasternak', 'Math', 3)
(1970, 'Stan Ambani', 'Econ', 0)
(1999, 'Peter Lynch', 'AppMath', 6)
(2142, 'Sabrina Zhou', 'DSI', 4)
(2143, 'Maya Abdul', 'Sociology', 3)
(2144, 'Karim Shiny', 'English', 5)
(2145, 'Valentino Love', 'Psychology', 4)
(2946, 'Steve Brown', 'Math', 9)
(3303, 'Jane Lynch', 'Philosophy', 3)


In [22]:
#point the path to where in your hard drive you have stored the file instructor.csv
data = pd.read_csv("instructor.csv")
data.head()

ID           name   dept_name  salary
0  111      Joe Smith         DSI  120000
1  112     Ying Zheng     CompSci  220000
2  113  Sunil Agarwal     AppMath   99000
3  114    Jennifer Lo     English   86000
4  115    Taylor Slow  Psychology   90000

In [23]:
data.dtypes

ID            int64
name         object
dept_name    object
salary        int64
dtype: object

In [24]:
for i,row in data.iterrows():
            sql = "INSERT INTO instructor VALUES (%s,%s,%s, %s)"
            mycursor.execute(sql, tuple(row))
            print("Record inserted")
            # the connection is not autocommitted by default, so we 
            # must commit to save our changes
            mydb.commit()

Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted


In [25]:
query = "SELECT * from instructor"
mycursor.execute(query)

In [26]:
for x in mycursor:
    print(x)

(111, 'Joe Smith', 'DSI', 120000)
(112, 'Ying Zheng', 'CompSci', 220000)
(113, 'Sunil Agarwal', 'AppMath', 99000)
(114, 'Jennifer Lo', 'English', 86000)
(115, 'Taylor Slow', 'Psychology', 90000)
(116, 'Friar Driver', 'English', 88000)
(117, 'Carmen Herman', 'DSI', 150000)
(118, 'Calista Holistic', 'CompSci', 123000)
(119, 'Rashid Irani', 'Psychology', 101000)


# Assignment Two

Part 1: Create Tables

In [27]:
mycursor = mydb.cursor()
mycursor.execute("DROP TABLE IF EXISTS data1050F24.course")
mycursor.execute('''CREATE TABLE data1050F24.course (
                    course_id VARCHAR(128) PRIMARY KEY,
                    title VARCHAR(128) NOT NULL,
                    dept_name VARCHAR(128),
                    credits INT,
                    foreign key(dept_name) references data1050F24.department(dept_name)
                    )''')

In [28]:
mycursor = mydb.cursor()
mycursor.execute("DROP TABLE IF EXISTS data1050F24.prereq")
mycursor.execute ('''
                  CREATE TABLE data1050F24.prereq (
                  course_id VARCHAR(128),
                  prereq_id VARCHAR(128),
                  PRIMARY KEY(course_id,prereq_id),
                  foreign key(course_id) references data1050F24.course(course_id),
                  foreign key(prereq_id) references data1050F24.course(course_id)
                  )''')

In [29]:
mycursor = mydb.cursor()
mycursor.execute("DROP TABLE IF EXISTS data1050F24.advisor")
mycursor.execute('''CREATE TABLE data1050F24.advisor (
                    s_id INT PRIMARY KEY,
                    i_id INT,
                    foreign key(s_id) references data1050F24.student(ID),
                    foreign key(i_id) references data1050F24.instructor(ID))
                    ''')

In [30]:
mycursor = mydb.cursor()
mycursor.execute("DROP TABLE IF EXISTS data1050F24.classroom")
mycursor.execute('''
                 CREATE TABLE data1050F24.classroom (
                 building VARCHAR(128),
                 room_no INT,
                 capacity INT,
                 check(capacity >= 0),
                 PRIMARY KEY(building,room_no)
                 );'''
                 )

In [31]:
mycursor = mydb.cursor()

mycursor.execute("SHOW TABLES")

for x in mycursor:
  print(x)

('advisor',)
('classroom',)
('course',)
('department',)
('instructor',)
('prereq',)
('student',)


Part 2: Populate Tables

In [32]:
#point the path to where in your hard drive you have stored the file course.csv
data = pd.read_csv("course.csv")
data.head()

course_id                        title dept_name  credits
0  Data1050             Data Engineering       DSI      1.0
1  Data1030        Hands-on data science       DSI      1.0
2  APMA1650      Statistical Inference 1   AppMath      1.0
3  CSCI1270  Database Management Systems   CompSci      1.0
4  Data1450                Text Analysis       DSI      1.0

In [33]:
data.dtypes

course_id     object
title         object
dept_name     object
credits      float64
dtype: object

In [34]:
for i,row in data.iterrows():
            sql = "INSERT INTO course VALUES (%s,%s,%s, %s)"
            mycursor.execute(sql, tuple(row))
            print("Record inserted")
            # the connection is not autocommitted by default, so we 
            # must commit to save our changes
            mydb.commit()

Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted


In [35]:
query = "SELECT * from course"
mycursor.execute(query)

In [36]:
for x in mycursor:
    print(x)

('APMA1650', 'Statistical Inference 1', 'AppMath', 1)
('CSCI1270', 'Database Management Systems', 'CompSci', 1)
('Data1030', 'Hands-on data science', 'DSI', 1)
('Data1050', 'Data Engineering', 'DSI', 1)
('Data1450', 'Text Analysis', 'DSI', 1)
('Data2050', 'Practicum', 'DSI', 1)
('Econ2180', 'Game Theory', 'Econ', 1)
('Econ9999', 'Mega Macro Economics', 'Econ', 2)
('Engl1631P', "Shakespeare's Girls", 'English', 1)
('Engl1760M', 'The miracle of Cinema', 'English', 1)
('Phil1635', 'Advanced Deductive Logic', 'Philosophy', 1)
('Phil2410', 'Moral Psychology', 'Philosophy', 1)
('Psyc1450', 'Human sexuality', 'Psychology', 2)
('Psyc2134', 'Intro to Cognitive Science', 'Psychology', 1)
('Soc1872O', 'Critical Race Theory', 'Sociology', 1)
('Soc1873D', 'Inequality in Infant Health', 'Sociology', 1)


In [37]:
#point the path to where in your hard drive you have stored the file prereq.csv
data = pd.read_csv("prereq.csv")
data.head()

course_id  prerq_id
0  Data2050  Data1050
1  Data2050  Data1030
2  Data1030  Data1050
3  Data1050  CSCI1270
4  Econ9999  Econ2180

In [38]:
data.dtypes

course_id    object
prerq_id     object
dtype: object

In [39]:
for i,row in data.iterrows():
            sql = "INSERT INTO prereq VALUES (%s,%s)"
            mycursor.execute(sql, tuple(row))
            print("Record inserted")
            # the connection is not autocommitted by default, so we 
            # must commit to save our changes
            mydb.commit()

Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted


In [40]:
query = "SELECT * from prereq"
mycursor.execute(query)

In [41]:
for x in mycursor:
    print(x)

('Data1050', 'CSCI1270')
('Data2050', 'Data1030')
('Data1030', 'Data1050')
('Data2050', 'Data1050')
('Econ9999', 'Econ2180')
('Econ2180', 'Phil1635')
('Soc1873D', 'Soc1872O')


In [42]:
#point the path to where in your hard drive you have stored the file advisor.csv
data = pd.read_csv("advisor.csv")
data.head()

s_id  i_id
0  1238   111
1  1333   111
2  2142   111
3  1645   117
4  1845   111

In [43]:
data.dtypes

s_id    int64
i_id    int64
dtype: object

In [44]:
for i,row in data.iterrows():
            sql = "INSERT INTO advisor VALUES (%s,%s)"
            mycursor.execute(sql, tuple(row))
            print("Record inserted")
            # the connection is not autocommitted by default, so we 
            # must commit to save our changes
            mydb.commit()

Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted


In [45]:
query = "SELECT * from advisor"
mycursor.execute(query)

In [46]:
for x in mycursor:
    print(x)

(1238, 111)
(1333, 111)
(1845, 111)
(2142, 111)
(1970, 113)
(1221, 115)
(1455, 116)
(2144, 116)
(1645, 117)


In [47]:
#point the path to where in your hard drive you have stored the file classroom.csv
data = pd.read_csv("classroom.csv")
data.head()

building  room_no  capacity
0    Sayles      128       100
1    Sayles      235        60
2  Franklin      212        90
3  Franklin      144        60
4    Angell      303        80

In [48]:
data.dtypes

building    object
room_no      int64
capacity     int64
dtype: object

In [49]:
for i,row in data.iterrows():
            sql = "INSERT INTO classroom VALUES (%s,%s,%s)"
            mycursor.execute(sql, tuple(row))
            print("Record inserted")
            # the connection is not autocommitted by default, so we 
            # must commit to save our changes
            mydb.commit()

Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted


In [50]:
query = "SELECT * from classroom"
mycursor.execute(query)

In [51]:
for x in mycursor:
    print(x)

('Angell', 303, 80)
('Angell', 370, 20)
('Angell', 405, 30)
('CIT', 312, 200)
('CIT', 320, 55)
('CIT', 404, 80)
('Franklin', 144, 60)
('Franklin', 212, 90)
('Pembroke', 111, 200)
('Pembroke', 231, 70)
('Sayles', 128, 100)
('Sayles', 235, 60)
('Skinner', 140, 80)
('Watson', 90, 90)


# Assignment Three

Part One: Create Tables

In [52]:
mycursor = mydb.cursor()
mycursor.execute("DROP TABLE IF EXISTS data1050F24.time_slot")
mycursor.execute('''
                 CREATE TABLE data1050F24.time_slot (
                 time_slot_id INT PRIMARY KEY,
                 day VARCHAR(128) not null,
                 start_time VARCHAR(5) not null,
                 end_time VARCHAR(5) not null
                 );'''
                 )

In [53]:
mycursor = mydb.cursor()
mycursor.execute("DROP TABLE IF EXISTS data1050F24.section")
mycursor.execute('''
                 CREATE TABLE data1050F24.section (
                 course_id VARCHAR(128),
                 sec_id INT,
                 semester VARCHAR(128),
                 year INT,
                 building VARCHAR(128),
                 room_no INT,
                 time_slot_id INT,
                 check(sec_id > 0),
                 PRIMARY KEY(course_id,sec_id,semester,year),
                 foreign key(building,room_no) references data1050F24.classroom(building,room_no),
                 foreign key(time_slot_id) references data1050F24.time_slot(time_slot_id)
                 );'''
                 )

In [54]:
mycursor = mydb.cursor()
mycursor.execute("DROP TABLE IF EXISTS data1050F24.teaches")
mycursor.execute('''
                 CREATE TABLE data1050F24.teaches (
                 ID INT,
                 course_id VARCHAR(128),
                 sec_id INT,
                 semester VARCHAR(128),
                 year INT,
                 PRIMARY KEY(ID,course_id,sec_id,semester,year),
                 foreign key(ID) references data1050F24.instructor(ID),
                 foreign key(course_id,sec_id,semester,year) references data1050F24.section(course_id,sec_id,semester,year)
                 );'''
                 )

In [55]:
mycursor = mydb.cursor()
mycursor.execute("DROP TABLE IF EXISTS data1050F24.takes")
mycursor.execute('''
                 CREATE TABLE data1050F24.takes (
                 ID INT,
                 course_id VARCHAR(128),
                 sec_id INT,
                 semester VARCHAR(128),
                 year INT,
                 grade CHAR(1),
                 PRIMARY KEY(ID,course_id,sec_id,semester,year),
                 foreign key(ID) references data1050F24.student(ID),
                 foreign key(course_id,sec_id,semester,year) references data1050F24.section(course_id,sec_id,semester,year)
                 );'''
                 )

Part 2: Populate Tables

In [56]:
import numpy as np

In [57]:
#point the path to where in your hard drive you have stored the file time_slot.csv
data = pd.read_csv("time_slot.csv")
data.head()

time_slot_id      day start_time end_time
0             1   Monday       9:00    11:00
1             2   Monday      11:00     1:00
2             3   Monday       1:00     3:00
3             4   Monday       3:00     5:00
4             5  Tuesday       9:00    11:00

In [58]:
data.dtypes

time_slot_id     int64
day             object
start_time      object
end_time        object
dtype: object

In [59]:
for i,row in data.iterrows():
            sql = "INSERT INTO time_slot VALUES (%s,%s,%s, %s)"
            mycursor.execute(sql, tuple(row))
            print("Record inserted")
            # the connection is not autocommitted by default, so we 
            # must commit to save our changes
            mydb.commit()

Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted


In [60]:
query = "SELECT * from time_slot"
mycursor.execute(query)

In [61]:
for x in mycursor:
    print(x)

(1, 'Monday', '9:00', '11:00')
(2, 'Monday', '11:00', '1:00')
(3, 'Monday', '1:00', '3:00')
(4, 'Monday', '3:00', '5:00')
(5, 'Tuesday', '9:00', '11:00')
(6, 'Tuesday', '11:00', '1:00')
(7, 'Tuesday', '1:00', '3:00')
(8, 'Wednesday', '9:00', '11:00')
(9, 'Wednesday', '11:00', '1:00')
(10, 'Wednesday', '1:00', '3:00')
(11, 'Wednesday', '3:00', '5:00')
(12, 'Thursday', '9:00', '11:00')
(13, 'Thursday', '11:00', '1:00')
(14, 'Thursday', '1:00', '3:00')
(15, 'Friday', '9:00', '11:00')
(16, 'Friday', '11:00', '1:00')
(17, 'Friday', '1:00', '3:00')
(18, 'Friday', '3:00', '5:00')


In [62]:
#point the path to where in your hard drive you have stored the file section.csv
data = pd.read_csv("section.csv", dtype = str) 
data.head()

course_id sec_id semester  year  building room_no time_slot_id
0  Data1050      1     Fall  2023  Franklin     212            8
1  Data1050      1     Fall  2022       CIT     404            3
2  Data1030      1     Fall  2023  Franklin     212            6
3  Data1030      1     Fall  2022  Franklin     212            6
4  APMA1650      1   Spring  2023    Sayles     128            3

In [63]:
data.dtypes

course_id       object
sec_id          object
semester        object
year            object
building        object
room_no         object
time_slot_id    object
dtype: object

In [64]:
data = data.replace({np.nan: None})

In [65]:
for i,row in data.iterrows():
            sql = "INSERT INTO section VALUES (%s,%s,%s,%s,%s,%s,%s)"
            mycursor.execute(sql, tuple(row))
            print("Record inserted")
            # the connection is not autocommitted by default, so we 
            # must commit to save our changes
            mydb.commit()

Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted


In [66]:
query = "SELECT * from section"
mycursor.execute(query)

In [67]:
for x in mycursor:
    print(x)

('APMA1650', 1, 'Spring', 2023, 'Sayles', 128, 3)
('CSCI1270', 1, 'Fall', 2023, 'CIT', 312, 6)
('CSCI1270', 2, 'Fall', 2023, None, None, 6)
('Data1030', 1, 'Fall', 2022, 'Franklin', 212, 6)
('Data1030', 1, 'Fall', 2023, 'Franklin', 212, 6)
('Data1050', 1, 'Fall', 2022, 'CIT', 404, 3)
('Data1050', 1, 'Fall', 2023, 'Franklin', 212, 8)
('Data1450', 1, 'Spring', 2024, None, None, None)
('Data2050', 1, 'Fall', 2023, None, None, None)
('Data2050', 1, 'Spring', 2023, None, None, None)
('Data2050', 1, 'Summer', 2023, None, None, None)
('Econ2180', 1, 'Spring', 2023, 'Skinner', 140, 7)
('Psyc2134', 1, 'Fall', 2023, 'Angell', 405, 6)
('Soc1872O', 1, 'Spring', 2023, 'Sayles', 128, 5)


In [68]:
#point the path to where in your hard drive you have stored the file teaches.csv
data = pd.read_csv("teaches.csv")
data.head()

ID course_id  sec_id semester  year
0  111  Data1050       1     Fall  2023
1  117  Data1050       1     Fall  2022
2  117  Data1030       1     Fall  2023
3  113  APMA1650       1   Spring  2023
4  112  CSCI1270       1     Fall  2023

In [69]:
data.dtypes

ID            int64
course_id    object
sec_id        int64
semester     object
year          int64
dtype: object

In [70]:
for i,row in data.iterrows():
            sql = "INSERT INTO teaches VALUES (%s,%s,%s,%s,%s)"
            mycursor.execute(sql, tuple(row))
            print("Record inserted")
            # the connection is not autocommitted by default, so we 
            # must commit to save our changes
            mydb.commit()

Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted


In [71]:
query = "SELECT * from teaches"
mycursor.execute(query)

In [72]:
for x in mycursor:
    print(x)

(113, 'APMA1650', 1, 'Spring', 2023)
(112, 'CSCI1270', 1, 'Fall', 2023)
(118, 'CSCI1270', 2, 'Fall', 2023)
(117, 'Data1030', 1, 'Fall', 2023)
(117, 'Data1050', 1, 'Fall', 2022)
(111, 'Data1050', 1, 'Fall', 2023)
(111, 'Data2050', 1, 'Fall', 2023)
(117, 'Data2050', 1, 'Spring', 2023)
(111, 'Data2050', 1, 'Summer', 2023)
(115, 'Psyc2134', 1, 'Fall', 2023)
(119, 'Psyc2134', 1, 'Fall', 2023)


In [73]:
#point the path to where in your hard drive you have stored the file takes.csv
data = pd.read_csv("takes.csv")
data.head()

ID course_id  sec_id semester  year grade
0  1238  Data1050       1     Fall  2022     A
1  1238  Data1030       1     Fall  2023   NaN
2  1333  Data1030       1     Fall  2022     A
3  1333  Data1050       1     Fall  2022     A
4  1333  APMA1650       1   Spring  2023     B

In [74]:
data.dtypes

ID            int64
course_id    object
sec_id        int64
semester     object
year          int64
grade        object
dtype: object

In [75]:
data = data.replace({np.nan: None})

In [76]:
for i,row in data.iterrows():
            sql = "INSERT INTO takes VALUES (%s,%s,%s,%s,%s,%s)"
            mycursor.execute(sql, tuple(row))
            print("Record inserted")
            # the connection is not autocommitted by default, so we 
            # must commit to save our changes
            mydb.commit()

Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted


In [77]:
query = "SELECT * from takes"
mycursor.execute(query)

In [78]:
for x in mycursor:
    print(x)

(1122, 'CSCI1270', 2, 'Fall', 2023, None)
(1122, 'Data1050', 1, 'Fall', 2023, None)
(1238, 'CSCI1270', 1, 'Fall', 2023, None)
(1238, 'Data1030', 1, 'Fall', 2023, None)
(1238, 'Data1050', 1, 'Fall', 2022, 'A')
(1333, 'APMA1650', 1, 'Spring', 2023, 'B')
(1333, 'CSCI1270', 1, 'Fall', 2023, None)
(1333, 'Data1030', 1, 'Fall', 2022, 'A')
(1333, 'Data1050', 1, 'Fall', 2022, 'A')
(1333, 'Data2050', 1, 'Fall', 2023, None)
(1845, 'CSCI1270', 2, 'Fall', 2023, None)
(1845, 'Data1050', 1, 'Fall', 2023, None)
(1888, 'CSCI1270', 1, 'Fall', 2023, None)
(1888, 'Data1050', 1, 'Fall', 2023, None)
(1934, 'Data1050', 1, 'Fall', 2023, None)
(1970, 'Data1050', 1, 'Fall', 2023, None)
(1999, 'CSCI1270', 1, 'Fall', 2023, None)
(1999, 'Data1050', 1, 'Fall', 2023, None)
(2142, 'CSCI1270', 1, 'Fall', 2023, None)
(2142, 'Data1050', 1, 'Fall', 2023, None)
(2143, 'Data1050', 1, 'Fall', 2023, None)
(2946, 'Data1050', 1, 'Fall', 2023, None)
(3303, 'Data1050', 1, 'Fall', 2023, None)


Part 3: SQL Query

In [79]:
query = '''SELECT S.ID, S.name
            FROM student S,takes T
            WHERE S.id = T.id 
            AND S.dept_name = 'DSI'
            AND T.course_id = 'Data1050'
            AND T.semester = 'Fall'
            AND T.year = 2023
         '''
mycursor.execute(query)

In [80]:
for x in mycursor: 
    print(x)

(1845, 'Jane Chen')
(2142, 'Sabrina Zhou')


# Assignment Four

Question 1: SQL Query
Find the id, title and section_id of all the courses being taught in Fall 2023.

In [81]:
query = ''' SELECT C.course_id, C.title, S.sec_id
            FROM course C
            INNER JOIN section S
            ON S.course_id = C.course_id
            WHERE S.semester = 'Fall'
            AND S.year = 2023;
         '''
mycursor.execute(query)

In [82]:
for x in mycursor: 
    print(x)

('Data2050', 'Practicum', 1)
('CSCI1270', 'Database Management Systems', 1)
('CSCI1270', 'Database Management Systems', 2)
('Data1030', 'Hands-on data science', 1)
('Psyc2134', 'Intro to Cognitive Science', 1)
('Data1050', 'Data Engineering', 1)


Question 2: SQL Query Find the id, title, section_id, and instructor name of all courses being taught in Fall 2023

In [83]:
query = ''' SELECT C.course_id, C.title, S.sec_id, I.name
            FROM course C
            INNER JOIN section S 
            ON S.course_id = C.course_id
            INNER JOIN teaches T 
            ON T.course_id = S.course_id 
            AND T.sec_id = S.sec_id 
            AND T.semester = S.semester 
            AND T.year = S.year
            INNER JOIN instructor I 
            ON T.ID = I.ID
            WHERE S.semester = 'Fall'
            AND S.year = 2023;
         '''
mycursor.execute(query)

In [84]:
for x in mycursor: 
    print(x)

('CSCI1270', 'Database Management Systems', 1, 'Ying Zheng')
('CSCI1270', 'Database Management Systems', 2, 'Calista Holistic')
('Data1030', 'Hands-on data science', 1, 'Carmen Herman')
('Data1050', 'Data Engineering', 1, 'Joe Smith')
('Data2050', 'Practicum', 1, 'Joe Smith')
('Psyc2134', 'Intro to Cognitive Science', 1, 'Taylor Slow')
('Psyc2134', 'Intro to Cognitive Science', 1, 'Rashid Irani')


Question 3: Write a SQL instruction to change (i.e., update) the time_slot_id of all courses which are 6 to 2. You may not delete these and insert new ones; use the update command.

In [85]:
query = '''     UPDATE section
                SET time_slot_id = 2
                WHERE time_slot_id = 6;
        '''
mycursor.execute(query)

In [86]:
for x in mycursor:
    print(x)

Question 4: Find the course id, title, section and start time of all courses taught in Fall 2022

In [87]:
query = ''' SELECT C.course_id, C.title, S.sec_id,T.start_time
            FROM course C
            INNER JOIN section S
            ON S.course_id = C.course_id
            INNER JOIN time_slot T
            ON s.time_slot_id = T.time_slot_id
            WHERE S.semester = 'Fall'
            AND S.year = 2022;
         '''  
mycursor.execute(query)

In [88]:
for x in mycursor:
    print(x)

('Data1030', 'Hands-on data science', 1, '11:00')
('Data1050', 'Data Engineering', 1, '1:00')


Question 5: Write a SQL instruction so that all students with ID 1238 and 1333 who have a null grade in any course, have their grade changed to 'A'.

In [89]:
# query = ''' WITH temp_cred AS
#              (SELECT credits
#              FROM course C
#              INNER JOIN takes T
#              ON C.course_id = T.course_id
#              WHERE T.ID IN (1238,1333))
#              SELECT credits
#              FROM temp_cred;
#         '''

In [90]:
query = ''' UPDATE takes T
            INNER JOIN student S
            ON T.ID = S.ID
            SET grade = 'A'
            WHERE grade IS NULL
            AND S.ID IN (1238,1333);
        '''
mycursor.execute(query)

Question 6: After executing this instruction write a query to make appropriate changes to the tot_credit of those students (that is, increment it by the credits assigned to those courses where the grade was changed.)

In [91]:
query = ''' SELECT tot_cred
            FROM student
            WHERE ID IN (1238,1333);
        '''
mycursor.execute(query) 

In [92]:
for x in mycursor:
    print(x)

(4,)
(7,)


In [93]:
query = ''' UPDATE student
            SET tot_cred = 6
            WHERE ID = 1238;
        '''
mycursor.execute(query)

In [94]:
for x in mycursor:
    print(x)

In [95]:
query = ''' UPDATE student
            SET tot_cred = 9
            WHERE ID = 1333;
        '''
mycursor.execute(query)

In [96]:
query = ''' SELECT tot_cred
            FROM student
            WHERE ID IN (1238,1333);
        '''
mycursor.execute(query)

In [97]:
for x in mycursor:
    print(x)

(6,)
(9,)


In [98]:
# query = ''' WITH temp_cred AS
#              (SELECT credits
#              FROM course C
#              INNER JOIN takes T
#              ON C.course_id = T.course_id
#              WHERE T.ID IN (1238 AND T.course_id NOT IN ('Data1050')
#              OR (1333 AND T.course_id NOT IN ('CSCI1270','Data2050'))

#             SELECT *
#             FROM temp_cred
#             # UPDATE student
#             # SET tot_cred = tot_cred + temp_cred
#             # WHERE ID IN (1238,1333);
# '''

Question 7: After executing the instructions for 4 and 5, write a query to return the ID and names of those students who have the most credits.

In [99]:
query = '''SELECT ID,name
            FROM student
            WHERE tot_cred IN 
                (SELECT MAX(tot_cred)
                FROM student);
        '''
mycursor.execute(query) 

In [100]:
for x in mycursor:
    print(x)

(1221, 'Ivan Petrov')
(1333, 'Mukesh Modi')
(1645, 'Jane Doe')
(2946, 'Steve Brown')


# Assignment Five

1. Find the names of all students who have taken or are currently taking (in Fall' 23) Data 1050.

In [101]:
query = ''' SELECT name
            FROM student
            INNER JOIN takes
            ON takes.ID = student.ID
            WHERE takes.course_id = 'Data1050';
            '''
mycursor.execute(query)

In [102]:
for x in mycursor:
    print(x)

('John Smith',)
('Mukesh Modi',)
('Julia Rodriguez',)
('Jane Chen',)
('Chuning Liu',)
('Boris Pasternak',)
('Stan Ambani',)
('Peter Lynch',)
('Sabrina Zhou',)
('Maya Abdul',)
('Steve Brown',)
('Jane Lynch',)


2. Find the names of students who have taken Data 1050 more than once. (This would also include students who are currently taking Data 1050 and have also taken it in a previous semester.)

In [123]:
query = ''' SELECT student.name
            FROM student
            INNER JOIN takes
            ON takes.ID = student.ID
            WHERE takes.course_id = 'Data1050'
            GROUP BY student.ID, student.name
            HAVING COUNT(takes.course_id) > 1;
'''
mycursor.execute(query)

In [124]:
for x in mycursor:
    print(x)

3. For each department, find the total number of students who have taken classes offered by that department in Fall, 22. Do not include any department for which this total number is less than 2.

In [105]:
query = ''' SELECT COUNT(DISTINCT S.ID) AS student_count, D.dept_name
            FROM department D
            INNER JOIN student S
            ON S.dept_name = D.dept_name
            INNER JOIN takes T
            ON T.ID = S.ID
            INNER JOIN course C
            ON T.course_id = C.course_id
            WHERE T.semester = 'Fall'
            AND T.year = 2022
            GROUP BY D.dept_name
            HAVING student_count >= 2;
            '''
mycursor.execute(query)

In [106]:
for x in mycursor:
    print(x)

(2, 'DSI')


4. For each instructor,  output the name of the instructor and the total number of students they have taught in any section of any course. That is, the total number of students they have ever taught.

In [107]:
query = ''' SELECT name, COUNT(*) as students_taught
            FROM instructor I
            INNER JOIN teaches T
            ON I.ID = T.ID
            INNER JOIN section S
            ON T.course_id = S.course_id 
            AND T.sec_id = S.sec_id 
            AND T.semester = S.semester 
            AND T.year = S.year
            INNER JOIN takes K
            ON K.course_id = S.course_id 
            AND K.sec_id = S.sec_id 
            AND K.semester = S.semester 
            AND K.year = S.year
            '''

In [ ]:
for x in mycursor:
    print(x)

5. Find the id and names of instructors who have taught the least number of students.

# Add Foreign Key (No Longer Necessary)

In [108]:
# query = ('ALTER TABLE data1050F24.student ADD foreign key(dept_name) references data1050F24.department(dept_name)')
#mycursor.execute(query)

In [109]:
# query = ('ALTER TABLE data1050F24.instructor ADD foreign key(dept_name) references data1050F24.department(dept_name)')
# mycursor.execute(query)

In [110]:
#query = ('ALTER TABLE data1050F24.course ADD foreign key(dept_name) references data1050F24.department(dept_name)')
#mycursor.execute(query)

In [111]:
#query = ('''ALTER TABLE data1050F24.prereq
        #   ADD foreign key(course_id) references data1050F24.course(course_id),
        #   ADD foreign key(prereq_id) references data1050F24.course(course_id)''')
# mycursor.execute(query)

In [112]:
# query = ('''ALTER TABLE
            # data1050F24.advisor ADD foreign key(s_id) references data1050F24.student(ID),
            # ADD foreign key(i_id) references data1050F24.instructor(ID)''')
# mycursor.execute(query)

In [113]:
# query = ('''ALTER TABLE
            # data1050F24.section ADD foreign key(building) references data1050F24.classroom(building),
            # ADD foreign key(room_no) references data1050F24.classroom(room_no),
            # ADD foreign key(time_slot_id) references data1050F24.time_slot(time_slot_id)''')
# mycursor.execute(query)

In [114]:
# query = ('''ALTER TABLE
            # data1050F24.teaches ADD foreign key(ID) references data1050F24.instructor(ID),
            # ADD foreign key(course_id) references data1050F24.section(course_id),
            # ADD foreign key(sec_id) references data1050F24.section(sec_id),
            # ADD foreign key(semester) references data1050F24.section(semester),
            # ADD foreign key(year) references data1050F24.section(year)
            # ''')
# mycursor.execute(query)

In [115]:
# query = ('''ALTER TABLE
            # data1050F24.takes ADD foreign key(ID) references data1050F24.student(ID),
            # ADD foreign key(course_id) references data1050F24.section(course_id),
            # ADD foreign key(sec_id) references data1050F24.section(sec_id),
            # ADD foreign key(semester) references data1050F24.section(semester),
            # ADD foreign key(year) references data1050F24.section(year)
            # ''')
# mycursor.execute(query)